[project]
name = "back-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "boto3>=1.43.83",
    "fastapi[standard]>=0.141.1",
    "firebase-admin>=7.5.0",
    "psycopg[binary]>=3.2.0",
    "sqlalchemy>=2.0.0",
]
