[project]
name = "back-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "alembic-postgresql-enum>=1.10.0",
    "boto3>=1.43.83",
    "fastapi[standard]>=0.141.1",
    "firebase-admin>=7.5.0",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.2.0",
    "python-dotenv>=1.2.2",
    "sqlmodel>=0.0.42",
]

[dependency-groups]
dev = [
    "rust-just>=1.58.0",
    "types-boto3[s3]>=1.43.94",
]

