"""update_task_event

Revision ID: 0362b439e0a3
Revises: f9bad349b8a5
Create Date: 2026-09-25 15:35:32.590226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0362b439e0a3'
down_revision: Union[str, Sequence[str], None] = 'f9bad349b8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskevent', sa.Column('task_status', sa.Enum('COMPLETED', 'NOT_STARTED', 'IN_PROGRESS', name='taskstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskevent', 'task_status')
    # ### end Alembic commands ###
