"""remove None id fields and add email field to user

Revision ID: 5a2e9a6a73b2
Revises: ebf2449f5fb4
Create Date: 2026-09-21 12:13:16.104403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a2e9a6a73b2'
down_revision: Union[str, Sequence[str], None] = 'ebf2449f5fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attachment_id'), 'attachment', ['id'], unique=False)
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_index(op.f('ix_reminder_id'), 'reminder', ['id'], unique=False)
    op.create_index(op.f('ix_task_id'), 'task', ['id'], unique=False)
    op.create_index(op.f('ix_taskevent_id'), 'taskevent', ['id'], unique=False)
    op.create_index(op.f('ix_timeblock_id'), 'timeblock', ['id'], unique=False)
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_timeblock_id'), table_name='timeblock')
    op.drop_index(op.f('ix_taskevent_id'), table_name='taskevent')
    op.drop_index(op.f('ix_task_id'), table_name='task')
    op.drop_index(op.f('ix_reminder_id'), table_name='reminder')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_index(op.f('ix_attachment_id'), table_name='attachment')
    # ### end Alembic commands ###
