"""update_task_models

Revision ID: 5ccac1b6a6de
Revises: 5a2e9a6a73b2
Create Date: 2026-09-22 22:28:29.853463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5ccac1b6a6de'
down_revision: Union[str, Sequence[str], None] = '5a2e9a6a73b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

task_status_enum = sa.Enum(
    "completed",
    "not started",
    "in_progress",
    name="taskstatus",
)

task_event_type_enum = sa.Enum(
    "created",
    "updated",
    "deleted",
    name="taskeventtype",
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    task_status_enum.create(bind, checkfirst=True)
    task_event_type_enum.create(bind, checkfirst=True)
    op.add_column('task', sa.Column('is_priority', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('needs_help', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               type_=task_status_enum,
               existing_nullable=False, 
               postgresql_using='"status"::text::taskstatus')
    op.drop_column('task', 'difficulty')
    op.drop_column('task', 'estimated_duration')
    op.drop_column('task', 'priority')
    op.add_column('taskevent', sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('taskevent', 'event_type',
               existing_type=sa.VARCHAR(),
               type_=task_event_type_enum,
               existing_nullable=False, 
               postgresql_using='"event_type"::text::taskeventtype')
    op.create_index(op.f('ix_taskevent_author_id'), 'taskevent', ['author_id'], unique=False)
    op.create_foreign_key(None, 'taskevent', 'user', ['author_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_constraint(None, 'taskevent', type_='foreignkey')
    op.drop_index(op.f('ix_taskevent_author_id'), table_name='taskevent')
    op.alter_column('taskevent', 'event_type',
               existing_type=task_event_type_enum,
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='"event_type"::text')
    op.drop_column('taskevent', 'author_id')
    op.add_column('task', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('task', 'status',
               existing_type=task_status_enum,
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='"status"::text')
    op.drop_column('task', 'deadline')
    op.drop_column('task', 'needs_help')
    op.drop_column('task', 'is_priority')
    
    task_event_type_enum.drop(bind, checkfirst=True)
    task_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
