"""device tokens, notification dismissal and enums

Revision ID: 9ff05ce483ed
Revises: 5a2e9a6a73b2
Create Date: 2026-09-21 23:25:42.822026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ff05ce483ed'
down_revision: Union[str, Sequence[str], None] = '5a2e9a6a73b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('created', 'started', 'completed', 'needs_help', name='event_type').create(op.get_bind())
    sa.Enum('deadline_soon', 'needs_help', 'priority', name='notification_kind').create(op.get_bind())
    op.create_table('devicetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicetoken_id'), 'devicetoken', ['id'], unique=False)
    op.create_index(op.f('ix_devicetoken_token'), 'devicetoken', ['token'], unique=True)
    op.create_index(op.f('ix_devicetoken_user_id'), 'devicetoken', ['user_id'], unique=False)
    op.add_column('reminder', sa.Column('dismissed_at', sa.DateTime(), nullable=True))
    op.alter_column('reminder', 'kind',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('deadline_soon', 'needs_help', 'priority', name='notification_kind'),
               existing_nullable=False,
               postgresql_using='kind::notification_kind')
    op.add_column('task', sa.Column('is_priority', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('task', sa.Column('needs_help', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.drop_column('task', 'difficulty')
    op.drop_column('task', 'estimated_duration')
    op.drop_column('task', 'priority')
    op.alter_column('taskevent', 'event_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('created', 'started', 'completed', 'needs_help', name='event_type'),
               existing_nullable=False,
               postgresql_using='event_type::event_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taskevent', 'event_type',
               existing_type=sa.Enum('created', 'started', 'completed', 'needs_help', name='event_type'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('task', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('estimated_duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task', 'deadline')
    op.drop_column('task', 'needs_help')
    op.drop_column('task', 'is_priority')
    op.alter_column('reminder', 'kind',
               existing_type=sa.Enum('deadline_soon', 'needs_help', 'priority', name='notification_kind'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('reminder', 'dismissed_at')
    op.drop_index(op.f('ix_devicetoken_user_id'), table_name='devicetoken')
    op.drop_index(op.f('ix_devicetoken_token'), table_name='devicetoken')
    op.drop_index(op.f('ix_devicetoken_id'), table_name='devicetoken')
    op.drop_table('devicetoken')
    sa.Enum('deadline_soon', 'needs_help', 'priority', name='notification_kind').drop(op.get_bind())
    sa.Enum('created', 'started', 'completed', 'needs_help', name='event_type').drop(op.get_bind())
    # ### end Alembic commands ###
