"""add screen load event

Revision ID: be47b5982fb7
Revises: d4f7a2c9e815
Create Date: 2026-10-01 20:04:14.632102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be47b5982fb7'
down_revision: Union[str, Sequence[str], None] = 'd4f7a2c9e815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenloadevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('load_time_ms', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenloadevent_id'), 'screenloadevent', ['id'], unique=False)
    op.create_index(op.f('ix_screenloadevent_user_id'), 'screenloadevent', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screenloadevent_user_id'), table_name='screenloadevent')
    op.drop_index(op.f('ix_screenloadevent_id'), table_name='screenloadevent')
    op.drop_table('screenloadevent')
    # ### end Alembic commands ###
