"""use enum names for task status and event type

Revision ID: e4ad9cb1728c
Revises: 96bd724e3b8c
Create Date: 2026-09-29 19:45:24.141419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'e4ad9cb1728c'
down_revision: Union[str, Sequence[str], None] = '96bd724e3b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: persist enum members by name (SQLAlchemy default)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskstatus',
        new_values=['COMPLETED', 'NOT_STARTED', 'IN_PROGRESS'],
        affected_columns=[TableReference(table_schema='public', table_name='task', column_name='status'), TableReference(table_schema='public', table_name='taskevent', column_name='task_status')],
        enum_values_to_rename=[
            ('completed', 'COMPLETED'),
            ('not started', 'NOT_STARTED'),
            ('in_progress', 'IN_PROGRESS'),
        ],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskeventtype',
        new_values=['CREATED', 'VIEWED', 'UPDATED', 'STATUS_CHANGED', 'DELETED'],
        affected_columns=[TableReference(table_schema='public', table_name='taskevent', column_name='event_type')],
        enum_values_to_rename=[
            ('created', 'CREATED'),
            ('viewed', 'VIEWED'),
            ('updated', 'UPDATED'),
            ('status_changed', 'STATUS_CHANGED'),
            ('deleted', 'DELETED'),
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: back to lowercase enum values."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskeventtype',
        new_values=['created', 'updated', 'deleted', 'viewed', 'status_changed'],
        affected_columns=[TableReference(table_schema='public', table_name='taskevent', column_name='event_type')],
        enum_values_to_rename=[
            ('CREATED', 'created'),
            ('VIEWED', 'viewed'),
            ('UPDATED', 'updated'),
            ('STATUS_CHANGED', 'status_changed'),
            ('DELETED', 'deleted'),
        ],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskstatus',
        new_values=['completed', 'not started', 'in_progress'],
        affected_columns=[TableReference(table_schema='public', table_name='task', column_name='status'), TableReference(table_schema='public', table_name='taskevent', column_name='task_status')],
        enum_values_to_rename=[
            ('COMPLETED', 'completed'),
            ('NOT_STARTED', 'not started'),
            ('IN_PROGRESS', 'in_progress'),
        ],
    )
    # ### end Alembic commands ###
