"""add screen load event

Revision ID: f43b973901b3
Revises: e4ad9cb1728c
Create Date: 2026-10-01 15:43:27.692283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43b973901b3'
down_revision: Union[str, Sequence[str], None] = 'e4ad9cb1728c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenloadevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('load_time_ms', sa.Float(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenloadevent_id'), 'screenloadevent', ['id'], unique=False)
    op.create_index(op.f('ix_screenloadevent_user_id'), 'screenloadevent', ['user_id'], unique=False)
    op.drop_column('group', 'deadline')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('deadline', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_screenloadevent_user_id'), table_name='screenloadevent')
    op.drop_index(op.f('ix_screenloadevent_id'), table_name='screenloadevent')
    op.drop_table('screenloadevent')
    # ### end Alembic commands ###
