"""remove-major

Revision ID: f9bad349b8a5
Revises: 5ccac1b6a6de
Create Date: 2026-09-23 03:39:31.222306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9bad349b8a5'
down_revision: Union[str, Sequence[str], None] = '5ccac1b6a6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'major')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
