STATUS_COMPLETED = "completed"
STATUS_NOT_STARTED = "not started"
STATUS_IN_PROGRESS = "in_progress"

EVENT_STARTED = "started"
EVENT_COMPLETED = "completed"

SECONDS_PER_MINUTE = 60

DEFAULT_TASK_DURATION_MINUTES = 60

BASED_ON_HISTORY = "historical_events"
BASED_ON_FALLBACK = "task_estimate"
